version: "2"

# Print all issues reported by all linters.
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  # We'll track the golangci-lint default linters manually
  # instead of letting them change without our control.
  default: none
  enable:
    # golangci-lint defaults:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Our own extras:
    - revive
    - nolintlint

  settings:

    errcheck:
      exclude-functions:
        # Writing a plain string to a fmt.State cannot fail.
        - io.WriteString(fmt.State)
        - fmt.Fprintf(fmt.State)

    govet:
      # These govet checks are disabled by default, but they're useful.
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite

  exclusions:
    generated: lax
    rules:
      # Don't warn on unused parameters.
      # Parameter names are useful; replacing them with '_' is undesirable.
      - linters: [revive]
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

      # staticcheck already has smarter checks for empty blocks.
      # revive's empty-block linter has false positives.
      # For example, as of writing this, the following is not allowed.
      #   for foo() { }
      - linters: [revive]
        text: 'empty-block: this block is empty, you can remove it'

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
